Parquery/icontract

icontract/_checkers.py, tests/test_invariant.py
This fixes possible race conditions since endless recursion blockers depend on global state which was not properly locked. The current fix uses thread-local storage with `threading.local()`. This also fixes #136.
=> fixed race conditions in endless recursion blockers

icontract/_checkers.py, tests/test_threading.py
This commit fixes #139. `threading.local()` can only store immutable
objects, while mutable objects are silently discarded. See
http://slinkp.com/python-thread-locals-20171201.html for more details.
This bug went unnoticed since there was no test that tested the behavior
of the contracts in a multi-threaded setting.
=> fixed bug related to threading.local and mutables

README.rst, benchmarks/against_dpcontracts/compare_invariant.py, benchmarks/against_dpcontracts/compare_postcondition.py, benchmarks/against_dpcontracts/compare_precondition.py, benchmarks/benchmark_2.0.7.rst, icontract/__init__.py, icontract/_checkers.py, icontract_meta.py, precommit.py, setup.py, tests/test_snapshot.py
This commit makes a couple of fixes to improve the computational
efficiency of the contracts. There was a performance regression when the
state was introduced (notably, `ExitStack` caused a lot of overhead).
This commit also introduces benchmarking into the continuous integration
(as part of the precommit.py script) so that we can continously monitor
the efficiency in the future.
Fixes #142 .
=> fixed performance regression due to state

README.rst, icontract_meta.py, setup.py
This adds `icontract_meta` module to `setup.py` which was erroneously forgotten in a previous commit.
The commit also bumps the version to 2.3.4.
This fixes #144 .
=> added icontract_meta to setup.py

README.rst
This patch reports handling of `*args` and `**kwargs` as a known issue
and asks the users to vote on its relevance.
This is directly related to issue #147.
=> remarked `*args` and `**kwargs` as known issue

README.rst, benchmarks/against_dpcontracts/compare_invariant.py, benchmarks/against_dpcontracts/compare_postcondition.py, benchmarks/against_dpcontracts/compare_precondition.py, precommit.py, tests/test_mypy_decorators.py, tests/test_precondition.py, tests/test_represent.py
This patch fixes quite some minor issues with the pre-commit script and
the unit tests so that they also run in Windows.
This finally enables contributors to work on Windows. Mind that the
library worked on Windows even before, so this change affects only the
*development*.
=> added support for development in Windows

README.rst, precommit.py
The utf-8 encoding was omitted when reading README.rst in
`precommit.py`.  This caused garbling of the file when the modified
content was written back. This patch fixes both the garbling and
`precommit.py`.
=> fixed missing encodings in precommit.py

README.rst, icontract/_checkers.py, tests/test_recursion.py
The invariant checks need to be disabled during the construction as
a call to a member function might trigger an invariant check on an
unitialized attribute.
Fixes #149.
=> disabled invariant checks during construction

CHANGELOG.rst, icontract_meta.py
* Disabled invariant checks during the construction to avoid attribute errors
on uninitialized attributes
=> bumped to version 2.3.5

benchmarks/against_dpcontracts/compare_invariant.py, benchmarks/against_dpcontracts/compare_postcondition.py, benchmarks/against_dpcontracts/compare_precondition.py, benchmarks/import_cost/classes_100_with_5_disabled_invariants.py, benchmarks/import_cost/functions_100_with_1_disabled_contract.py, benchmarks/import_cost/measure.py, benchmarks/import_cost/runme.py
Benchmark scripts were not included in the precommit.py. This change
merely reformats them, while their inclusion in precommit.py will
happen in a future pull request.
=> Formatted benchmark scripts

benchmark.py, precommit.py
We had to separate benchmark.py from precommit.py since it became
difficult to mantain dependencies on the remote CI servers. Now the
benchmarks are always run locally while the remote CI only runs
formatting, mypy and other checks.
=> separated benchmark.py from precommit.py

icontract/__init__.py, setup.py
We had to denormalize icontract_meta module (which used to be
referenced from setup.py and this file) since readthedocs had problems
with installing icontract through pip on their servers with imports in
setup.py.
This patch finally removes icontract_meta as it is not used anymore.
=> Denormalized icontract_meta

icontract/__init__.py, setup.py
* Denormalized icontract_meta so that icontract can be installed on
readthedocs.
=> Bumped to 2.3.6

.github/workflows/publish-to-pypi.yml
This patch introduces a GitHub workflow to automatically package the
code and publish it to PyPi.
=> Set up release workflow on GitHub

icontract/_represent.py, setup.py
This change is just standard maintenance of the dependencies. There is
no particular reason why mypy was updated.
=> Updated mypy to 0.790

.travis.yml, icontract/_recompute.py, icontract/_represent.py, precommit.py, tests_3_8/__init__.py, tests_3_8/test_represent.py
Named expressions were [introduced recently in Python 3.8][1].
This patch updates icontract's representation module so that they can be
properly recomputed and represented in the violation messages.
Fixes #164.
[1]: https://www.python.org/dev/peps/pep-0572/
=> Added support for named expressions in contracts

README.rst, icontract/_checkers.py, tests/test_invariant.py
The dunder `__new__` is a special class method which is not marked with
`classmethod` decorator. We therefore can not wrap it with invariant
checker, but the current logic failed to detect it.
Fixes #167.
=> Exempted `__new__` from invariant checks

icontract/_recompute.py, icontract/_represent.py, precommit.py, tests_3_6/__init__.py, tests_3_6/test_represent.py, tests_3_8/__init__.py
The f-strings (a.k.a. literal string interpolation) is a feature in
Python 3.6 which was not supported in the recompute module of icontract.
This patch adds the recomputation and representation of the f-strings.
Fixes #169.
=> Added support for recomputation of f-strings

icontract/_checkers.py, tests/test_invariant.py, tests_3_8/test_invariant.py
This patch introduces a special handling of `namedtuple` class. Namely,
`namedtuple` leverages `__new__` to create new tuples and merely calls
`object.__init__` as constructor. Therefore we can not simply wrap
`__init__` as it is a slot wrapper and will break the implementation of
`namedtuple`.
Fixes #171.
=> Added invariants to namedtuple

tests_3_7/__init__.py, tests_3_7/test_invariant.py
This patch adds test with `dataclasses.dataclass` decoretor to verify
that the invariants are correctly handled. This is because it turned out
there was a bug when handling named tuples (see issue #171).
=> Tested with `dataclasses.dataclass`

README.rst, setup.py, tests/test_typeguard.py
This patch introduces tests to make sure that icontract and typeguard
can play well together. Additionally, we hint in the Readme that users
should use typeguard instead of icontract whenever they already
annotated the code with type annotations.
This is related to issue #174 .
=> Tested with typeguard

README.rst, icontract/_checkers.py, tests/test_args_and_kwargs_in_contract.py
Certain conditions need to handle variable postiional or keyword
arguments of the function call. Currently, contracts could not refer to
them and thus the functions without explicitly named arguments could not
be decorated.
This patch introduces two special arguments populated by icontract for
the condition function: `_ARGS`, which captures all the positional
arguments in the function call, and `_KWARGS`, which captures the
keyword arguments, respectively.
Fixes #147.
=> Added special arguments `_ARGS` and `_KWARGS`

icontract/_metaclass.py, mypy.ini
This patch integrates with icontract-hypothesis (and consequently
Hypothesis) by registering all DBC classes with Hypothesis.
This is necessary so that precondition considerations are propagated in
Hypothesis build strategies.
=> Integrated with icontract-hypothesis

CHANGELOG.rst, icontract/__init__.py, setup.py
Integrated with icontract-hypothesis (#179)
* Refactored for icontract-hypothesis (#178)
* Added special arguments `_ARGS` and `_KWARGS` (#176)
* Tested with typeguard (#175)
* Tested with `dataclasses.dataclass` (#173)
* Added invariants to namedtuple (#172)
* Added support for recomputation of f-strings (#170)
* Exempted `__new__` from invariant checks (#168)
* Added support for named expressions in contracts (#166)
=> Bumped to 2.4.0

icontract/_checkers.py, icontract/_represent.py, tests/test_for_integrators.py
This patch introduces a test suite meant to document what downstream
integrators (such as static validators, documentation tools *etc.*)
should use.
The patch also includes a refactoring so that the interface is more
ergonomic to use.
=> Refactored and added tests for integrators

icontract/_metaclass.py
DBC metaclass automatically registered with Hypothesis even though
Hypothesis was not used. This creates an unnecessary overhead so a hook
is provided to be monkey-patched downstream (*e.g.*, by
icontract-hypothesis).
=> Removed automatic registration with Hypothesis

CHANGELOG.rst, icontract/__init__.py
*  Removed automatic registration with Hypothesis and replaced it
with a hook that downstream libraries such as icontract-hypothesis
can use (#181)
* Refactored and added tests for integrators (#182)
=> Bumped to 2.4.1

setup.py
This was forgotten in the previous commit by mistake.
=> Updated version to 2.4.1 in setup.py

README.rst, icontract/_checkers.py, tests/test_invariant.py
While we handled `classmethod` correctly when decorating the class with
invariants checkers, we omitted to check for `staticmethod`'s.
This patch adds additional checks for `staticmethod`'s and skips to
decorate them with invariant checker.
Fixes #186.
=> Handled static methods appropriately

docs/source/benchmarks.rst, icontract/_checkers.py
We had to in-line `_assert_*` and `_capture` functions to improve
readability as separated functions lead to bugs which were hard to
reason about (as the logic of the call was separated in the source code
from its implementation).
This patch also prepares the ground for adding support for async
functions and async conditions.
=> In-lined assert and capture functions

docs/source/async.rst, docs/source/index.rst, icontract/_checkers.py, icontract/_decorators.py, icontract/_represent.py, tests/test_postcondition.py, tests/test_precondition.py, tests/test_snapshot.py, tests_3_8/test_async.py
This patch introduces the support for both async functions (as
decoratees) and for async conditions (and snapshots).
This is important for downstream libraries such as [fastapi-icontract]
that are make heavy use of async functions.
[fastapi-icontract]: https://github.com/mristin/fastapi-icontract/
=> Added support for async

tests/test_typeguard.py
This patch forces mypy to ignore a line where we explicitly introduce an
error to test that the icontract plays well with the typeguard library.
=> Fixed mypy on typeguard unit test

docs/source/async.rst, icontract/_checkers.py, icontract/_decorators.py, icontract/_recompute.py, tests_3_8/test_async.py
Previously, we expected the condition to always return a materialized
check. This patch allows the condition to return a coroutine so that it
is awaited before the value is evaluated.
This allows the user to specify conditions that work around the lack of
async lambda in the language.
=> Added support for coroutine

docs/source/usage.rst, icontract/_checkers.py, icontract/_decorators.py, icontract/_types.py, setup.py, tests/test_error.py
This patch allows the user to supply error as an instance of
``BaseException``. This is practical for cases where the error is fixed
and need not be re-instantiated on every violation.
An additional benefit is that the syntax is a bit shorter than with a
argument-less callable (one `lambda: ` less).
=> Added support for error-as-instance

icontract/_checkers.py, icontract/_decorators.py, icontract/_represent.py, icontract/_types.py, tests/test_for_integrators.py
This patch introduces a mechanism for downstream integrators to add
manually contracts and snapshots to the function checker.
=> Encapsulate adding contracts for integrators

README.rst, docs/source/introduction.rst
This patch adds a reference to fastapi-icontracts in the readme and in
the docs as the initial version has been released.
=> Referenced fastapi-icontracts in docs

docs/source/async.rst, setup.py, tests_3_8/async/test_coroutine_example.py
This patch simplifies the docs for async conditions by replacing custom
functions with asyncstdlib ones.
=> Referenced asyncstdlib in docs

mypy.ini, setup.py, tests_3_8/async/test_coroutine_example.py
Travis stopped running continuous integration, so a couple of minor
issues slipped through.
This patch fixes these minor issues. The move of the continuous
integration to GitHub is implemented in a following commit.
=> Fixed minor issues missed for lack of CI

icontract/_checkers.py, icontract/_recompute.py, icontract/_represent.py, tests/test_for_integrators.py, tests/test_represent.py, tests_3_8/async/test_postcondition.py, tests_3_8/async/test_precondition.py
If the recomputation of a failed condition raised an exception, the user
was left in the dark which condition triggered the exception.
This patch adds a more informative message, so that the user can at
least inspect the problematic condition or send us a better bug report.
=> Added better reporting on recompute failure

icontract/_recompute.py, tests/test_represent.py
We re-compute the generator expression by recompilcation. However, we do
descend to display the external inputs of the generator expression, and
ignore the placeholder.
If there was a function call on one or more placeholders, the
re-computation will fail with a cryptic message.
This patch fixes the issue.
=> Fixed recomputation of calls in generator expr

icontract/_metaclass.py, tests/test_inheritance_precondition.py
We need to handle `__new__` diffrently from other functions as it is a
constructor. Hence it does not relate directly to the class hierarchy
and can define its own pre- and post-conditions.
=> Allowed `__new__` to tighten pre-conditions

CHANGELOG.rst, icontract/__init__.py, setup.py
* Allowed `__new__` to tighten pre-conditions (#211)
* Fixed recomputation of calls in generator expr (#210)
* Added better reporting on recompute failure (#207)
=> Released 2.5.1

icontract/_checkers.py, tests/test_invariant.py, tests/test_precondition.py
This patch fixes a bug caused when `self` is passed as a keyword
arguments instead as a positional argument..
Usually, `self` is passed as a positional argument so this bug went
unnoticed for a long time. Notably, preconditions and postconditions
worked fine, but the problem surfaced when unbounding an instance method
and passing `self` as keyword argument explicitly.
=> Fixed handling of `self` when passed as kwarg

icontract/_checkers.py, icontract/_represent.py, tests/test_postcondition.py, tests/test_precondition.py
Many times in production or debugging it was hard to discern what caused
the violation of the contract since only the condition arguments were
represented in the violation message. This is often not enough to
identify the test case or to give us a hint what might have provoked the
bug.
This patch represents all the arguments of the function call at the time
of violation so that the bugs are easier to trace.
=> Added reporting of all arguments on violation

icontract/__init__.py, icontract/_checkers.py, icontract/_decorators.py, icontract/_metaclass.py, icontract/_recompute.py, icontract/_represent.py, icontract/_types.py, mypy.ini, pylint.rc, setup.py, tests/test_checkers.py, tests/test_for_integrators.py, tests/test_inheritance_precondition.py, tests/test_precondition.py, tests/test_recompute.py, tests/test_represent.py, tests_3_6/test_represent.py, tests_3_8/test_represent.py
Having conditions using `all` quantifiers is useful to catch bugs, but
it is very cumbersome to trace back what caused the `all` to fail.
This patch implements a tracing of the generator expression in all and
reports the first example in the comprehension which was falsy.
=> Added tracing of `all` on generator expressions

CHANGELOG.rst, icontract/__init__.py, setup.py
* Fixed handling of `self` when passed as kwarg (#213)
* Added reporting of all arguments on violation (#214)
* Added tracing of `all` on generator expressions (#215)
=> Released 2.5.2

icontract/_represent.py
The changes in #214 were not properly documented in the docstring of the
function `collect_variable_lookup` in `_represent` module.
=> Fixed docstring for `collect_variable_lookup`

icontract/_recompute.py, pylint.rc, requirements.txt, tests/test_represent.py
So far, the re-computation stopped at generator expressions. However,
there might have been relevant parts which should be re-computed beneath
the AST of the generator expression.
This patch handles propagation of `PLACEHOLDER`'s and allows the
re-computation visitor to visit all the descendant AST nodes.
=> Propagated placeholders in re-computation

README.rst, docs/source/usage.rst, icontract/_represent.py, tests/test_args_and_kwargs_in_contract.py, tests/test_inheritance_invariant.py, tests/test_inheritance_postcondition.py, tests/test_inheritance_precondition.py, tests/test_inheritance_snapshot.py, tests/test_invariant.py, tests/test_postcondition.py, tests/test_precondition.py, tests/test_snapshot.py, tests/test_typeguard.py, tests_3_6/test_represent.py, tests_3_8/async/test_args_and_kwargs_in_contract.py, tests_3_8/test_error.py
The previous fix, #214, actually did not resolve the issue, but the
missing effects went unnoticed due to omitted closer inspection of unit
tests.
Eventually it became apparent that the #214 was buggy. This is a
post-fix of #214 followed by a closer inspection and adaptation
of unit tests.
=> Fixed reporting all arguments on violation

README.rst, docs/source/usage.rst, tests/test_inheritance_invariant.py, tests/test_invariant.py, tests/test_postcondition.py, tests/test_precondition.py, tests/test_represent.py
This patch makes all the unit tests use `textwrap` for easier
readability when we compare multi-line texts.
This should also provide a hint to the developers in the future how to
deal with multi-line texts.
=> Unified text comparisons in tests with `textwrap`

CHANGELOG.rst, icontract/__init__.py, setup.py
* Fixed reporting all arguments on violation (#219)
* Propagated placeholders in re-computation (#218)
* Fixed docstring for `collect_variable_lookup` (#217)
=> Released 2.5.3

docs/source/recipes.rst
This patch mentions that the introduction of the walrus operator
(PEP 572) was controversial and cautions the reader to be careful about
abusing it.
=> Added note about Walrus Operator controversy

icontract/_checkers.py, icontract/_metaclass.py, icontract/_recompute.py, icontract/_represent.py, pylint.rc, setup.py, tests/test_args_and_kwargs_in_contract.py, tests/test_error.py, tests/test_for_integrators.py, tests/test_inheritance_invariant.py, tests/test_inheritance_postcondition.py, tests/test_inheritance_precondition.py, tests/test_invariant.py, tests/test_mypy_decorators.py, tests/test_recursion.py, tests/test_typeguard.py, tests_3_7/test_invariant.py, tests_3_8/async/test_args_and_kwargs_in_contract.py, tests_3_8/async/test_exceptions.py, tests_3_8/async/test_invariant.py, tests_3_8/async/test_postcondition.py, tests_3_8/async/test_precondition.py, tests_3_8/test_error.py, tests_3_8/test_invariant.py
Upgraded to mypy 0.910 and pylint 2.9.6
This patch upgrades the mypy to 0.910. This was necessary so that we can
test the type inference with the latest mypy.
We also had to upgrade pylint 2.9.6 since the checks broke on CI due to
astroid having hard time parsing `_metaclass.py`. Due to this upgrade,
we had to disable all `no-member` warnings from pylint as pylint did not
properly infer types in condition functions.
Related to #224.
=> Upgraded to mypy 0.910

icontract/_checkers.py, icontract/_decorators.py, icontract/_globals.py, tests/test_mypy_decorators.py
The current type annotation of the `invariant` decorator did not use
generics. This patch makes it more specific so that a generic
``TypeVar`` bounded by ``type`` is used in order to help downstream
tools work better.
Related to #224.
=> Made invariant type annotation more specific

setup.py
Python 3.5 could not be supported since neither mypy nor pylint support
Python 3.5 anymore. Python 3.5 reached end-of-life in 2020, so more
dependencies are probably affected as well.
This change simply removes the corresponding tag in the distribution.
The continous integration only tested for >= 3.6 Python versions anyhow.
=> Removed tag for Python 3.5

icontract/_recompute.py, mypy.ini, setup.py, tests/test_represent.py
The numpy arrays do not like `PLACEHOLDER in arr` which will cause a
`ValueError`. However, we tested for `PLACEHOLDER` everywhere using
`in` operator in the representation module.
This patch fixes the problem by using explicit `any(...)` and checking
also explicitly for `... is PLACEHOLDER`. In contrast, `in` operator
uses equality (`==`) instead of identity (`is`), which was not the
desirable behavior anyhow originally.
Fixes #229.
=> Fixed representation of numpy arrays

CHANGELOG.rst, icontract/__init__.py, setup.py
* Fixed representation of numpy arrays (#232)
* Removed tag for Python 3.5 (#231)
=> Released 2.5.5

icontract/_recompute.py, icontract/_represent.py, tests/test_represent.py, tests_3_8/test_error.py
With this patch, whenever a contract violation occurs, the subscripts
(such as `arr[x]`) will be included in the error message.
=> Added representation of subscripts

.github/workflows/ci.yml, .gitignore, icontract/_metaclass.py, icontract/_recompute.py, setup.py, tests/test_checkers.py, tests/test_inheritance_postcondition.py, tests/test_inheritance_precondition.py, tests/test_precondition.py
This patch introduces Python versions 3.9 and 3.10 in continuous
integration as well as minor fixes caused by the deprecations in
these new versions.
Also fixes #235.
=> Added support for Python 3.9 and 3.10

setup.py
The test directories `tests_*` are erronously included in the package. With this patch they are excluded in the package building.
Fixes #239.
=> Excluded all tests from package

docs/source/benchmarks.rst, docs/source/introduction.rst, docs/source/usage.rst, icontract/_checkers.py, icontract/_metaclass.py, icontract/_represent.py
We fixed typos in various places in the documentation and docstrings.
=> Fixed typos in documentation

benchmark.py, docs/source/benchmarks.rst, setup.py, tests_with_others/test_deal.py
We updated the benchmarks and tests to compare with the newest deal
version 4.23.3 for up-to-date comparison between the features and
computational efficiency.
Fixes #244.
=> Updated benchmarks and tests to use deal 4.23.3

requirements-doc.txt
We had to upgrade the sphinx since its dependency jinja2 caused problems
due to deprecations.
=> Upgraded to latest sphinx 5

icontract/_represent.py, setup.py
Mypy complained that ``asttokens.ASTTokens`` is missing with the newest
asttokens version (2.0.7). Honestly, we are at loss what caused this
error as ``asttokens/__init__.py`` did not change. We tried updating
mypy to the latest version (0.971) which did not fix the error either.
We are leaving mypy set to the latest version and fix the mypy error by
explicitly writing ``asttokens.asttokens.ASTTokens`` instead of
``asttokens.ASTTokens``. While it is ugly, it is a quick fix for now.
=> Fixed mypy error on missing ``asttokens.ASTTokens``

.github/workflows/publish-to-pypi.yml, .gitignore
We added wheels to the releases since some systems are not allowed to
install source distributions.
Directly related to #250.
=> Added wheels to releases

.github/workflows/ci.yml, setup.py
Since Python 3.6 is deprecated on GitHub CI servers, we can not test for it anymore. Therefore, we remove it from the list of supported Python versions.
=> Deprecated Python 3.6

precommit.py, tests_3_6/__init__.py, tests_3_6/test_represent.py, tests_with_others/test_deal.py, tests_with_others/test_dpcontracts.py
We forgot to include the above-mentioned directories in the pre-commit script. In this patch, we fix the formatting and make sure all the pre-commit checks pass for these directories as well.
=> Included `tests_3_6` and `tests_3_7` in precommit

icontract/_checkers.py, precommit.py, tests_3_8/async/separately_test_concurrent.py
Previously, we used `threading.local()` to keep track of contracts which are in progress of verification to allow for recursive contracts. While this works for threads, this approach does not work with async coroutines.
In this fix we use `contextvars` instead of `threading.local()` to manage the context, and keep track of concurrent contracts and function calls.
Fixes #255.
=> Fixed in-progress set for async

precommit.py, setup.py
We excluded black from development dependencies for Python 3.7 as black dropped support for Python 3.7 (due to its EOL) and only supports Python versions from 3.8 on.
=> Excluded black from dev for Python 3.7

icontract/_recompute.py, pylint.rc, setup.py, tests/test_args_and_kwargs_in_contract.py, tests/test_error.py, tests/test_for_integrators.py, tests/test_inheritance_invariant.py, tests/test_inheritance_postcondition.py, tests/test_inheritance_precondition.py, tests/test_invariant.py, tests/test_postcondition.py, tests/test_precondition.py, tests/test_recompute.py, tests/test_recursion.py, tests/test_represent.py, tests/test_snapshot.py, tests/test_threading.py, tests/test_typeguard.py, tests_3_6/test_represent.py, tests_3_8/async/separately_test_concurrent.py, tests_3_8/async/test_args_and_kwargs_in_contract.py, tests_3_8/async/test_recursion.py, tests_3_8/test_error.py, tests_3_8/test_represent.py
We upgraded pylint to the latest version to keep up with its development. Eventually, we want to support Python 3.11, so this upgrade is timely as well.
=> Upgraded to pylint 2.17.5

setup.py
We upgraded pydocstyle, a development dependency, to its latest version 6.3.0. We did that in order to keep up with its development as part of
the continuous maintenance of this library.
=> Upgraded pydocstyle to 6.3.0

requirements-doc.txt, requirements.txt, setup.py
We removed the license, readme and requirements.txt from setup.py as they are not really necessary, and only clutter the distribution.
Fixes #254.
=> Removed meta data files from setup.py

CHANGELOG.rst, icontract/__init__.py, setup.py
* Removed meta data files from setup.py (#262)
* Added support for python 3.11 (#260)
* Fixed in-progress set for async (#256)
=> Released 2.6.3

setup.py
The support for Python 3.6 has been dropped in #257 as GitHub removed its support in the CI pipeline. With this patch, we restored the support of Python 3.6. Notably, we had to add the package `contextvars` conditioned on Python 3.6.
=> Restored Python 3.6 support

benchmarks/against_others/compare_invariant.py, benchmarks/against_others/compare_postcondition.py, benchmarks/against_others/compare_precondition.py, icontract/_recompute.py, icontract/_represent.py, precommit.py, setup.py, tests/test_represent.py
We replaced YAPF with black in #265, but forgot to update the comments to turn formatting off on a small number of snippets where the default formatting was unreadable.
In this patch, we replaced the comments to instruct black to skip these snippets.
=> Replaced YAPF comments with black comments

setup.py
Before, we used ternary operations on lists in Python code of `setup.py` to conditionally add development dependencies based on the Python version.
In this patch, we replaced this code with requirements specifiers, which substantially simplified the code in `setup.py`.
=> Simplified `extras_require` in `setup.py`

CHANGELOG.rst, icontract/__init__.py, setup.py
* Restored Python 3.6 support (#274)
The support for Python 3.6 has been dropped in #257 as GitHub removed its support in the CI pipeline. With this patch, we restored the support of Python 3.6. Notably, we had to add the package ``contextvars`` conditioned on Python 3.6.
=> Released 2.6.4

setup.py
We list Python 3.11 to the list of supported Python versions as it has been already included in the continuous integration, and proved to work.
=> Added Python 3.11 to the list of supported Pythons

CHANGELOG.rst, icontract/__init__.py, setup.py
* Added Python 3.11 to the list of supported Pythons (#280)
* Fixed deal dependency marker (#279)
This patch is important as we silently broke ``setup.py``, which was tolerated by older versions of setuptools, but not any more by the newer ones. With this patch, icontract's ``setup.py`` is made valid again.
=> Released 2.6.5

CHANGELOG.rst, icontract/__init__.py, setup.py
* Updated typeguard and deal to latest versions (#284)
This change is needed so that distributions can successfully run the necessary tests with the development dependencies. Previously, the dependencies were outdated, and the old versions were already deprecated in distributions (notably, typegard and deal).
=> Released 2.6.6

docs/source/development.rst
=> Added commit message style in development.rst

docs/source/known_issues.rst, tests_3_7/test_invariant.py
In this patch, we test for `dataclasses` which use `field`'s to define default values. Originally, we thought that there are issues with data classes in general due to the issue #288, but it turned out that the order of decorators matters (``dataclass`` first).
We tested everything, and documented the order of the decorators accordingly.
Fixes #288.
=> Tested for data classes with fields

.readthedocs.yml
The ``build.os`` needs to be set in the readthedocs configuration file, see https://github.com/readthedocs/readthedocs.org/issues/8912.
=> Fixed readthedocs

setup.py
We received error messages in older version of the coverage so we upgrade to 6.5.0 which seems to work well with coveralls and all the supported Python versions.
See this run for more details:
https://github.com/Parquery/icontract/actions/runs/9779072024/job/26997391256?pr=292
=> Upgrade coverage to 6.5.0

docs/source/api.rst, docs/source/usage.rst, icontract/__init__.py, icontract/_checkers.py, icontract/_decorators.py, icontract/_types.py, precommit.py, pylint.rc, tests/test_invariant.py, tests_3_7/test_invariant.py
Originally, we had enforced invariants only at calls to "normal" methods, and excluded ``__setattr__`` since it is usually too expensive to verify invariants whenever setting an attribute.
However, there are use cases where the users prefer to incur to computational overhead for correctness. To that end, we introduced the feature in this patch to steer when the invariants are enforced (at method calls, on setting attributes, or in both situations).
Fixes #291.
=> Allowed to enforce invariants on attribute setting

CHANGELOG.rst, icontract/__init__.py, setup.py
* Allowed to enforce invariants on attribute setting (#292)
Originally, we had enforced invariants only at calls to "normal" methods, and excluded ``__setattr__`` since it is usually too expensive to verify invariants whenever setting an attribute.
However, there are use cases where the users prefer to incur to computational overhead for correctness. To that end, we introduced the feature to steer when the invariants are enforced (at method calls, on setting attributes, or in both situations).
=> Released 2.7.0

docs/source/usage.rst, tests/test_invariant.py
If the base class does not inherit from ``DBC`` or uses ``DBCMeta`` as the meta class, inheritance of invariants will be broken.
In this patch, we tested and documented this unexpected behavior to warn the users about this foot-gun.
=> Tested and documented undefined inheritance

icontract/_checkers.py, icontract/_metaclass.py, tests/test_inheritance_invariant.py
With pull request #292, we allowed users to specify the events which trigger the invariant checks for each individual invariant.
This introduced a bug where invariants added to a child class were also added to a parent class.
In this patch, we fixed the issue.
Fixes #295.
=> Fixed invariants leak between related classes

CHANGELOG.rst, icontract/__init__.py, setup.py
* Fixed invariants leak between related classes (#297)
This is a critical bugfix patch version. We introduced a bug in 2.7.0 (#292) where invariants defined on derived classes leaked up to parent classes. This bug is fixed in this version.
=> Released 2.7.1
