icontract/_checkers.py, icontract/_decorators.py, icontract/_globals.py, icontract/_types.py, tests/test_mypy_decorators.py
=> specified require and ensure to use generics

README.rst, icontract/_decorators.py, icontract/_types.py, tests/test_inheritance_invariant.py, tests/test_inheritance_postcondition.py, tests/test_inheritance_precondition.py, tests/test_inheritance_snapshot.py, tests/test_invariant.py, tests/test_postcondition.py, tests/test_precondition.py, tests/test_represent.py, tests/test_snapshot.py, tests/violation_error.py
=> added location to require, ensure and snapshot

icontract/_checkers.py, tests/test_invariant.py, tests/test_postcondition.py, tests/test_precondition.py
=> missing boolyness caught with more informative exception

icontract/_checkers.py, icontract/_decorators.py, icontract/_types.py, tests/test_invariant.py, tests/test_postcondition.py, tests/test_precondition.py
=> distinguished between optional and mandatory arguments in conditions

icontract/_checkers.py, tests/test_precondition.py
=> improved error message on unexpected argument

.travis.yml, README.rst, icontract/_metaclass.py, icontract/_recompute.py, setup.py, tox.ini
=> made compatible with Python 3.8

README.rst, benchmarks/against_others/compare_invariant.py, benchmarks/against_others/compare_postcondition.py, benchmarks/against_others/compare_precondition.py, mypy.ini, precommit.py, setup.py, tests_with_others/test_deal.py, tests_with_others/test_dpcontracts.py
This change compares the features and the performance of the icontract
with the latest version of the `deal` library.
=> compared against `deal`

icontract/_recompute.py
This patch fixes the visiting of different classes of constants in
the AST which was deprecated in Python 3.8. The backward
compatibility with Python 3.5, 3.6 and 3.7 is still maintained.
Fixes #160 .
=> Acted on deprecated warnings in `ast` module

icontract/_checkers.py, icontract/_represent.py
This refactoring has been performed to facilitate integration with
Hypothesis package. The integration between icontract and Hypothesis
will be implemented in a separate PyPI package (not icontract).
=> Refactored for icontract-hypothesis

README.rst
Changed:
- png gitter badge to svg one
- python's return type style
=> Improved README.rst a bit

README.rst
This patch adds a link to repl.it post so that readers can test the
library live in their browser.
Co-authored-by: Kyle Lawlor-Bagcal <wgwz@pm.me>
=> Linked examples from Readme to repl.it

CHANGELOG.rst, icontract/__init__.py, setup.py
* Encapsulated adding contracts for integrators (#202)
* Added support for error-as-instance (#201)
* Added support for coroutine (#197)
* Added support for async (#196)
=> Released 2.5.0

README.rst, docs/source/async.rst, docs/source/conf.py, docs/source/index.rst, docs/source/introduction.rst, docs/source/recipes.rst
This adds the recipes to the documentation and references the
Python-by-contract corpus.
=> Documented recipes

tests/test_mypy_decorators.py
This patch adds a test case to make sure that class invariants do not
break the type inference with mypy.
Related to #224.
=> Tested decoartors for preserving mypy types

CHANGELOG.rst, icontract/__init__.py, setup.py
* Made type annotation for `invariant` decorator more specific (#227)
=> Released 2.5.4

CHANGELOG.rst, icontract/__init__.py, setup.py
* Added support for Python 3.9 and 3.10 (#236)
* Added representation of subscripts (#237)
=> Released 2.6.0

CHANGELOG.rst, icontract/__init__.py, setup.py
*  Excluded all tests from package (#240)
=> Released 2.6.1

icontract/_metaclass.py, icontract/_represent.py, pylint.rc, setup.py, tests/test_invariant.py, tests/test_mypy_decorators.py
We updated mypy and pylint to their respective latest versions since
some of their dependencies have been deprecated in the meanwhile.
=> Updated to mypy 0.950 and pylint 2.13.9

CHANGELOG.rst, icontract/__init__.py, setup.py
* Added wheels to releases (#251)
* Fixed mypy error on missing ``asttokens.ASTTokens`` (#252)
=> Released 2.6.2

icontract/_checkers.py, setup.py, tests/test_inheritance_postcondition.py, tests/test_inheritance_precondition.py, tests/test_inheritance_snapshot.py, tests/test_mypy_decorators.py, tests/test_postcondition.py, tests/test_precondition.py
We faced a bug in mypy 0.971 related to positional arguments (see [1]).
In this fix, we simply upgrade mypy to the latest version which fixes the issue.
[1]: https://github.com/python/mypy/issues/13627
=> Upgraded mypy to 0.991

setup.py
Origin: https://github.com/pdm-project/pdm/issues/2338
=> Fixed deal dependency marker
